name: Build Frida TS to JS

on:
  workflow_dispatch:
  push:
    paths:
      - "agent.ts"
      - "package.json"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos do repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Buildar agent.ts para agent.js
        run: npm run build

      - name: Enviar JS compilado
        uses: actions/upload-artifact@v4
        with:
          name: agent-js-compilado
          path: agent.js
